---
# Summary:
# This playbook will do:
# 1. Create VM
# 2. Update VM
# 3. Fetch VM
# 4. Delete VM

- name: VM crud playbook
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false
  tasks:
    - name: Setting Variables
      ansible.builtin.set_fact:
        vm_name: "VM name"
        cluster_uuid: "00062899-4a29-0cf9-0000-000000022f54"
        vm_uuid: "a990cfaa-95a8-4861-bdf6-14060555442d"

    - name: Create VM
      ntnx_vms_v2:
        name: "{{ vm_name }}"
        description: "vm description"
        cluster:
          ext_id: "{{ cluster_uuid }}"
        num_sockets: 1
        num_cores_per_socket: 1
        num_threads_per_core: 1
        num_numa_nodes: 1
        memory_size_bytes: 4294967296
        is_vcpu_hard_pinning_enabled: false
        is_cpu_passthrough_enabled: false
        is_memory_overcommit_enabled: false
        is_gpu_console_enabled: false
        is_vga_console_enabled: false
        machine_type: PC
        hardware_clock_timezone: UTC
        enabled_cpu_features:
          - HARDWARE_VIRTUALIZATION
        is_branding_enabled: false
        is_agent_vm: false
        apc_config:
          is_apc_enabled: false
        vtpm_config:
          is_vtpm_enabled: false
      register: result
      ignore_errors: true

    - name: Update VM
      ntnx_vms_v2:
        state: present
        ext_id: "{{ vm_uuid }}"
        name: "{{ vm_name }}"
        description: "vm description"
        cluster:
          ext_id: "{{ cluster_uuid }}"
        num_sockets: 1
        num_cores_per_socket: 1
        num_threads_per_core: 1
        num_numa_nodes: 1
        memory_size_bytes: 4294967296
        is_vcpu_hard_pinning_enabled: false
        is_cpu_passthrough_enabled: false
        is_memory_overcommit_enabled: false
        is_gpu_console_enabled: false
        is_vga_console_enabled: false
        machine_type: PC
        hardware_clock_timezone: UTC
        enabled_cpu_features:
          - HARDWARE_VIRTUALIZATION
        is_branding_enabled: false
        is_agent_vm: false
        apc_config:
          is_apc_enabled: false
        vtpm_config:
          is_vtpm_enabled: false
      register: result
      ignore_errors: true

    - name: Fetch VM
      ntnx_vms_info_v2.py:
        ext_id: "{{ vm_uuid }}"
      register: result
      ignore_errors: true

    - name: Delete VM
      ntnx_vms_v2:
        state: absent
        ext_id: "{{ vm_uuid }}"
      register: result
      ignore_errors: true
