---
name: ansible-lint
on:
  - pull_request

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x (latest)
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
